[
uuid(b0562d52-b292-4918-aaba-379847e00bc5),
version(1.0)
]

interface Game
{
	void GetServerInfo(
		[out]					long* size,
		[out, size_is(, *size)] wchar_t** outString
	);

	int TryLoggin(
		[in]					long* size,
		[in , size_is(, *size)]	wchar_t** alias
	);
}
